### ISSUE TITLE
Contributor Signup

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/globia-relmia#1]
If you would like to help contribute to this project, please comment on this issue so that I can tag you in the future on other issues and PRs.

**Comment by youugotssponged** [comment]
I'm up for contributing to this project - youugotssponged

**Comment by linuxuser07** [comment]
I'm up for contributing to this project

**Comment by cmgriffing** [comment]
If someone wants to take this task on https://github.com/cmgriffing/piratey/issues/12 for adding the fonts, head on over there and comment so I can assign it to you.

After the fonts are there we can get the header going with https://github.com/cmgriffing/piratey/issues/17.
